name: Generate ASCII Artwork

on:
    push:

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
            -   name: checkout repo
                uses: actions/checkout@v5

            -   name: Install cowsay
                run: sudo apt-get update && sudo apt-get install cowsay -y

            -   name: Execute cowsay
                run: cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt

            -   name: Verify Output
                run: grep -i "dragon" dragon.txt
            
            -   name: Display Artwork
                run: cat dragon.txt

            -   name: List Repo Files
                run: ls -ltra
                